// Code generated by goctl. DO NOT EDIT.
// Source: example.proto

package server

import (
	"context"

	"github.com/suyuan32/simple-admin-example-rpc/example"
	"github.com/suyuan32/simple-admin-example-rpc/internal/logic/base"
	"github.com/suyuan32/simple-admin-example-rpc/internal/logic/student"
	"github.com/suyuan32/simple-admin-example-rpc/internal/svc"
)

type ExampleServer struct {
	svcCtx *svc.ServiceContext
	example.UnimplementedExampleServer
}

func NewExampleServer(svcCtx *svc.ServiceContext) *ExampleServer {
	return &ExampleServer{
		svcCtx: svcCtx,
	}
}

func (s *ExampleServer) InitDatabase(ctx context.Context, in *example.Empty) (*example.BaseResp, error) {
	l := base.NewInitDatabaseLogic(ctx, s.svcCtx)
	return l.InitDatabase(in)
}

// Student management
func (s *ExampleServer) CreateOrUpdateStudent(ctx context.Context, in *example.StudentInfo) (*example.BaseResp, error) {
	l := student.NewCreateOrUpdateStudentLogic(ctx, s.svcCtx)
	return l.CreateOrUpdateStudent(in)
}

func (s *ExampleServer) GetStudentList(ctx context.Context, in *example.StudentPageReq) (*example.StudentListResp, error) {
	l := student.NewGetStudentListLogic(ctx, s.svcCtx)
	return l.GetStudentList(in)
}

func (s *ExampleServer) DeleteStudent(ctx context.Context, in *example.IDReq) (*example.BaseResp, error) {
	l := student.NewDeleteStudentLogic(ctx, s.svcCtx)
	return l.DeleteStudent(in)
}

func (s *ExampleServer) BatchDeleteStudent(ctx context.Context, in *example.IDsReq) (*example.BaseResp, error) {
	l := student.NewBatchDeleteStudentLogic(ctx, s.svcCtx)
	return l.BatchDeleteStudent(in)
}

// Teacher management
func (s *ExampleServer) CreateOrUpdateTeacher(ctx context.Context, in *example.TeacherInfo) (*example.BaseResp, error) {
	l := logic.NewCreateOrUpdateTeacherLogic(ctx, s.svcCtx)
	return l.CreateOrUpdateTeacher(in)
}

func (s *ExampleServer) GetTeacherList(ctx context.Context, in *example.TeacherPageReq) (*example.TeacherListResp, error) {
	l := logic.NewGetTeacherListLogic(ctx, s.svcCtx)
	return l.GetTeacherList(in)
}

func (s *ExampleServer) DeleteTeacher(ctx context.Context, in *example.UUIDReq) (*example.BaseResp, error) {
	l := logic.NewDeleteTeacherLogic(ctx, s.svcCtx)
	return l.DeleteTeacher(in)
}

func (s *ExampleServer) BatchDeleteTeacher(ctx context.Context, in *example.UUIDsReq) (*example.BaseResp, error) {
	l := logic.NewBatchDeleteTeacherLogic(ctx, s.svcCtx)
	return l.BatchDeleteTeacher(in)
}
