// Code generated by goctl. DO NOT EDIT.
// Source: example.proto

package server

import (
	"context"

	"github.com/suyuan32/simple-admin-example-rpc/example"
	"github.com/suyuan32/simple-admin-example-rpc/internal/logic/example/base"
	"github.com/suyuan32/simple-admin-example-rpc/internal/logic/example/student"
	"github.com/suyuan32/simple-admin-example-rpc/internal/svc"
)

type ExampleServer struct {
	svcCtx *svc.ServiceContext
	example.UnimplementedExampleServer
}

func NewExampleServer(svcCtx *svc.ServiceContext) *ExampleServer {
	return &ExampleServer{
		svcCtx: svcCtx,
	}
}

func (s *ExampleServer) InitDatabase(ctx context.Context, in *example.Empty) (*example.BaseResp, error) {
	l := base.NewInitDatabaseLogic(ctx, s.svcCtx)
	return l.InitDatabase(in)
}

// Student management
func (s *ExampleServer) CreateStudent(ctx context.Context, in *example.StudentInfo) (*example.BaseResp, error) {
	l := student.NewCreateStudentLogic(ctx, s.svcCtx)
	return l.CreateStudent(in)
}

func (s *ExampleServer) UpdateStudent(ctx context.Context, in *example.StudentInfo) (*example.BaseResp, error) {
	l := student.NewUpdateStudentLogic(ctx, s.svcCtx)
	return l.UpdateStudent(in)
}

func (s *ExampleServer) GetStudentList(ctx context.Context, in *example.StudentListReq) (*example.StudentListResp, error) {
	l := student.NewGetStudentListLogic(ctx, s.svcCtx)
	return l.GetStudentList(in)
}

func (s *ExampleServer) GetStudentById(ctx context.Context, in *example.IDReq) (*example.StudentInfo, error) {
	l := student.NewGetStudentByIdLogic(ctx, s.svcCtx)
	return l.GetStudentById(in)
}

func (s *ExampleServer) DeleteStudent(ctx context.Context, in *example.IDsReq) (*example.BaseResp, error) {
	l := student.NewDeleteStudentLogic(ctx, s.svcCtx)
	return l.DeleteStudent(in)
}
