// Code generated by ent, DO NOT EDIT.

package ent

// set field if value is not empty. e.g. string does not equal to ""
func (s *StudentUpdate) SetNotEmptyName(value string) *StudentUpdate {
	if value != "" {
		return s.SetName(value)
	}
	return s
}

// set field if value is not empty. e.g. string does not equal to ""
func (s *StudentUpdateOne) SetNotEmptyName(value string) *StudentUpdateOne {
	if value != "" {
		return s.SetName(value)
	}
	return s
}

// set field if value is not empty. e.g. string does not equal to ""
func (s *StudentUpdate) SetNotEmptyAge(value int) *StudentUpdate {
	if value != 0 {
		return s.SetAge(value)
	}
	return s
}

// set field if value is not empty. e.g. string does not equal to ""
func (s *StudentUpdateOne) SetNotEmptyAge(value int) *StudentUpdateOne {
	if value != 0 {
		return s.SetAge(value)
	}
	return s
}

// set field if value is not empty. e.g. string does not equal to ""
func (s *StudentUpdate) SetNotEmptyAgeInt32(value int32) *StudentUpdate {
	if value != 0 {
		return s.SetAgeInt32(value)
	}
	return s
}

// set field if value is not empty. e.g. string does not equal to ""
func (s *StudentUpdateOne) SetNotEmptyAgeInt32(value int32) *StudentUpdateOne {
	if value != 0 {
		return s.SetAgeInt32(value)
	}
	return s
}

// set field if value is not empty. e.g. string does not equal to ""
func (s *StudentUpdate) SetNotEmptyAgeInt64(value int64) *StudentUpdate {
	if value != 0 {
		return s.SetAgeInt64(value)
	}
	return s
}

// set field if value is not empty. e.g. string does not equal to ""
func (s *StudentUpdateOne) SetNotEmptyAgeInt64(value int64) *StudentUpdateOne {
	if value != 0 {
		return s.SetAgeInt64(value)
	}
	return s
}

// set field if value is not empty. e.g. string does not equal to ""
func (s *StudentUpdate) SetNotEmptyAgeUint(value uint) *StudentUpdate {
	if value != 0 {
		return s.SetAgeUint(value)
	}
	return s
}

// set field if value is not empty. e.g. string does not equal to ""
func (s *StudentUpdateOne) SetNotEmptyAgeUint(value uint) *StudentUpdateOne {
	if value != 0 {
		return s.SetAgeUint(value)
	}
	return s
}

// set field if value is not empty. e.g. string does not equal to ""
func (s *StudentUpdate) SetNotEmptyAgeUint32(value uint32) *StudentUpdate {
	if value != 0 {
		return s.SetAgeUint32(value)
	}
	return s
}

// set field if value is not empty. e.g. string does not equal to ""
func (s *StudentUpdateOne) SetNotEmptyAgeUint32(value uint32) *StudentUpdateOne {
	if value != 0 {
		return s.SetAgeUint32(value)
	}
	return s
}

// set field if value is not empty. e.g. string does not equal to ""
func (s *StudentUpdate) SetNotEmptyAgeUint64(value uint64) *StudentUpdate {
	if value != 0 {
		return s.SetAgeUint64(value)
	}
	return s
}

// set field if value is not empty. e.g. string does not equal to ""
func (s *StudentUpdateOne) SetNotEmptyAgeUint64(value uint64) *StudentUpdateOne {
	if value != 0 {
		return s.SetAgeUint64(value)
	}
	return s
}

// set field if value is not empty. e.g. string does not equal to ""
func (s *StudentUpdate) SetNotEmptyWeightFloat(value float64) *StudentUpdate {
	if value != 0 {
		return s.SetWeightFloat(value)
	}
	return s
}

// set field if value is not empty. e.g. string does not equal to ""
func (s *StudentUpdateOne) SetNotEmptyWeightFloat(value float64) *StudentUpdateOne {
	if value != 0 {
		return s.SetWeightFloat(value)
	}
	return s
}

// set field if value is not empty. e.g. string does not equal to ""
func (s *StudentUpdate) SetNotEmptyWeightFloat32(value float32) *StudentUpdate {
	if value != 0 {
		return s.SetWeightFloat32(value)
	}
	return s
}

// set field if value is not empty. e.g. string does not equal to ""
func (s *StudentUpdateOne) SetNotEmptyWeightFloat32(value float32) *StudentUpdateOne {
	if value != 0 {
		return s.SetWeightFloat32(value)
	}
	return s
}

// set field if value is not empty. e.g. string does not equal to ""
func (t *TeacherUpdate) SetNotEmptyName(value string) *TeacherUpdate {
	if value != "" {
		return t.SetName(value)
	}
	return t
}

// set field if value is not empty. e.g. string does not equal to ""
func (t *TeacherUpdateOne) SetNotEmptyName(value string) *TeacherUpdateOne {
	if value != "" {
		return t.SetName(value)
	}
	return t
}

// set field if value is not empty. e.g. string does not equal to ""
func (t *TeacherUpdate) SetNotEmptyAge(value int) *TeacherUpdate {
	if value != 0 {
		return t.SetAge(value)
	}
	return t
}

// set field if value is not empty. e.g. string does not equal to ""
func (t *TeacherUpdateOne) SetNotEmptyAge(value int) *TeacherUpdateOne {
	if value != 0 {
		return t.SetAge(value)
	}
	return t
}

// set field if value is not empty. e.g. string does not equal to ""
func (t *TeacherUpdate) SetNotEmptyAgeInt32(value int32) *TeacherUpdate {
	if value != 0 {
		return t.SetAgeInt32(value)
	}
	return t
}

// set field if value is not empty. e.g. string does not equal to ""
func (t *TeacherUpdateOne) SetNotEmptyAgeInt32(value int32) *TeacherUpdateOne {
	if value != 0 {
		return t.SetAgeInt32(value)
	}
	return t
}

// set field if value is not empty. e.g. string does not equal to ""
func (t *TeacherUpdate) SetNotEmptyAgeInt64(value int64) *TeacherUpdate {
	if value != 0 {
		return t.SetAgeInt64(value)
	}
	return t
}

// set field if value is not empty. e.g. string does not equal to ""
func (t *TeacherUpdateOne) SetNotEmptyAgeInt64(value int64) *TeacherUpdateOne {
	if value != 0 {
		return t.SetAgeInt64(value)
	}
	return t
}

// set field if value is not empty. e.g. string does not equal to ""
func (t *TeacherUpdate) SetNotEmptyAgeUint(value uint) *TeacherUpdate {
	if value != 0 {
		return t.SetAgeUint(value)
	}
	return t
}

// set field if value is not empty. e.g. string does not equal to ""
func (t *TeacherUpdateOne) SetNotEmptyAgeUint(value uint) *TeacherUpdateOne {
	if value != 0 {
		return t.SetAgeUint(value)
	}
	return t
}

// set field if value is not empty. e.g. string does not equal to ""
func (t *TeacherUpdate) SetNotEmptyAgeUint32(value uint32) *TeacherUpdate {
	if value != 0 {
		return t.SetAgeUint32(value)
	}
	return t
}

// set field if value is not empty. e.g. string does not equal to ""
func (t *TeacherUpdateOne) SetNotEmptyAgeUint32(value uint32) *TeacherUpdateOne {
	if value != 0 {
		return t.SetAgeUint32(value)
	}
	return t
}

// set field if value is not empty. e.g. string does not equal to ""
func (t *TeacherUpdate) SetNotEmptyAgeUint64(value uint64) *TeacherUpdate {
	if value != 0 {
		return t.SetAgeUint64(value)
	}
	return t
}

// set field if value is not empty. e.g. string does not equal to ""
func (t *TeacherUpdateOne) SetNotEmptyAgeUint64(value uint64) *TeacherUpdateOne {
	if value != 0 {
		return t.SetAgeUint64(value)
	}
	return t
}

// set field if value is not empty. e.g. string does not equal to ""
func (t *TeacherUpdate) SetNotEmptyWeightFloat(value float64) *TeacherUpdate {
	if value != 0 {
		return t.SetWeightFloat(value)
	}
	return t
}

// set field if value is not empty. e.g. string does not equal to ""
func (t *TeacherUpdateOne) SetNotEmptyWeightFloat(value float64) *TeacherUpdateOne {
	if value != 0 {
		return t.SetWeightFloat(value)
	}
	return t
}

// set field if value is not empty. e.g. string does not equal to ""
func (t *TeacherUpdate) SetNotEmptyWeightFloat32(value float32) *TeacherUpdate {
	if value != 0 {
		return t.SetWeightFloat32(value)
	}
	return t
}

// set field if value is not empty. e.g. string does not equal to ""
func (t *TeacherUpdateOne) SetNotEmptyWeightFloat32(value float32) *TeacherUpdateOne {
	if value != 0 {
		return t.SetWeightFloat32(value)
	}
	return t
}
