// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	uuid "github.com/gofrs/uuid/v5"
)

// set field if value's pointer is not nil.
func (s *StudentUpdate) SetNotNilUpdatedAt(value *time.Time) *StudentUpdate {
	if value != nil {
		return s.SetUpdatedAt(*value)
	}
	return s
}

// set field if value's pointer is not nil.
func (s *StudentUpdateOne) SetNotNilUpdatedAt(value *time.Time) *StudentUpdateOne {
	if value != nil {
		return s.SetUpdatedAt(*value)
	}
	return s
}

// set field if value's pointer is not nil.
func (s *StudentCreate) SetNotNilUpdatedAt(value *time.Time) *StudentCreate {
	if value != nil {
		return s.SetUpdatedAt(*value)
	}
	return s
}

// set field if value's pointer is not nil.
func (s *StudentUpdate) SetNotNilName(value *string) *StudentUpdate {
	if value != nil {
		return s.SetName(*value)
	}
	return s
}

// set field if value's pointer is not nil.
func (s *StudentUpdateOne) SetNotNilName(value *string) *StudentUpdateOne {
	if value != nil {
		return s.SetName(*value)
	}
	return s
}

// set field if value's pointer is not nil.
func (s *StudentCreate) SetNotNilName(value *string) *StudentCreate {
	if value != nil {
		return s.SetName(*value)
	}
	return s
}

// set field if value's pointer is not nil.
func (s *StudentUpdate) SetNotNilAge(value *int) *StudentUpdate {
	if value != nil {
		return s.SetAge(*value)
	}
	return s
}

// set field if value's pointer is not nil.
func (s *StudentUpdateOne) SetNotNilAge(value *int) *StudentUpdateOne {
	if value != nil {
		return s.SetAge(*value)
	}
	return s
}

// set field if value's pointer is not nil.
func (s *StudentCreate) SetNotNilAge(value *int) *StudentCreate {
	if value != nil {
		return s.SetAge(*value)
	}
	return s
}

// set field if value's pointer is not nil.
func (s *StudentUpdate) SetNotNilAgeInt32(value *int32) *StudentUpdate {
	if value != nil {
		return s.SetAgeInt32(*value)
	}
	return s
}

// set field if value's pointer is not nil.
func (s *StudentUpdateOne) SetNotNilAgeInt32(value *int32) *StudentUpdateOne {
	if value != nil {
		return s.SetAgeInt32(*value)
	}
	return s
}

// set field if value's pointer is not nil.
func (s *StudentCreate) SetNotNilAgeInt32(value *int32) *StudentCreate {
	if value != nil {
		return s.SetAgeInt32(*value)
	}
	return s
}

// set field if value's pointer is not nil.
func (s *StudentUpdate) SetNotNilAgeInt64(value *int64) *StudentUpdate {
	if value != nil {
		return s.SetAgeInt64(*value)
	}
	return s
}

// set field if value's pointer is not nil.
func (s *StudentUpdateOne) SetNotNilAgeInt64(value *int64) *StudentUpdateOne {
	if value != nil {
		return s.SetAgeInt64(*value)
	}
	return s
}

// set field if value's pointer is not nil.
func (s *StudentCreate) SetNotNilAgeInt64(value *int64) *StudentCreate {
	if value != nil {
		return s.SetAgeInt64(*value)
	}
	return s
}

// set field if value's pointer is not nil.
func (s *StudentUpdate) SetNotNilAgeUint(value *uint) *StudentUpdate {
	if value != nil {
		return s.SetAgeUint(*value)
	}
	return s
}

// set field if value's pointer is not nil.
func (s *StudentUpdateOne) SetNotNilAgeUint(value *uint) *StudentUpdateOne {
	if value != nil {
		return s.SetAgeUint(*value)
	}
	return s
}

// set field if value's pointer is not nil.
func (s *StudentCreate) SetNotNilAgeUint(value *uint) *StudentCreate {
	if value != nil {
		return s.SetAgeUint(*value)
	}
	return s
}

// set field if value's pointer is not nil.
func (s *StudentUpdate) SetNotNilAgeUint32(value *uint32) *StudentUpdate {
	if value != nil {
		return s.SetAgeUint32(*value)
	}
	return s
}

// set field if value's pointer is not nil.
func (s *StudentUpdateOne) SetNotNilAgeUint32(value *uint32) *StudentUpdateOne {
	if value != nil {
		return s.SetAgeUint32(*value)
	}
	return s
}

// set field if value's pointer is not nil.
func (s *StudentCreate) SetNotNilAgeUint32(value *uint32) *StudentCreate {
	if value != nil {
		return s.SetAgeUint32(*value)
	}
	return s
}

// set field if value's pointer is not nil.
func (s *StudentUpdate) SetNotNilAgeUint64(value *uint64) *StudentUpdate {
	if value != nil {
		return s.SetAgeUint64(*value)
	}
	return s
}

// set field if value's pointer is not nil.
func (s *StudentUpdateOne) SetNotNilAgeUint64(value *uint64) *StudentUpdateOne {
	if value != nil {
		return s.SetAgeUint64(*value)
	}
	return s
}

// set field if value's pointer is not nil.
func (s *StudentCreate) SetNotNilAgeUint64(value *uint64) *StudentCreate {
	if value != nil {
		return s.SetAgeUint64(*value)
	}
	return s
}

// set field if value's pointer is not nil.
func (s *StudentUpdate) SetNotNilWeightFloat(value *float64) *StudentUpdate {
	if value != nil {
		return s.SetWeightFloat(*value)
	}
	return s
}

// set field if value's pointer is not nil.
func (s *StudentUpdateOne) SetNotNilWeightFloat(value *float64) *StudentUpdateOne {
	if value != nil {
		return s.SetWeightFloat(*value)
	}
	return s
}

// set field if value's pointer is not nil.
func (s *StudentCreate) SetNotNilWeightFloat(value *float64) *StudentCreate {
	if value != nil {
		return s.SetWeightFloat(*value)
	}
	return s
}

// set field if value's pointer is not nil.
func (s *StudentUpdate) SetNotNilWeightFloat32(value *float32) *StudentUpdate {
	if value != nil {
		return s.SetWeightFloat32(*value)
	}
	return s
}

// set field if value's pointer is not nil.
func (s *StudentUpdateOne) SetNotNilWeightFloat32(value *float32) *StudentUpdateOne {
	if value != nil {
		return s.SetWeightFloat32(*value)
	}
	return s
}

// set field if value's pointer is not nil.
func (s *StudentCreate) SetNotNilWeightFloat32(value *float32) *StudentCreate {
	if value != nil {
		return s.SetWeightFloat32(*value)
	}
	return s
}

// set field if value's pointer is not nil.
func (s *StudentUpdate) SetNotNilClassID(value *uuid.UUID) *StudentUpdate {
	if value != nil {
		return s.SetClassID(*value)
	}
	return s
}

// set field if value's pointer is not nil.
func (s *StudentUpdateOne) SetNotNilClassID(value *uuid.UUID) *StudentUpdateOne {
	if value != nil {
		return s.SetClassID(*value)
	}
	return s
}

// set field if value's pointer is not nil.
func (s *StudentCreate) SetNotNilClassID(value *uuid.UUID) *StudentCreate {
	if value != nil {
		return s.SetClassID(*value)
	}
	return s
}

// set field if value's pointer is not nil.
func (s *StudentUpdate) SetNotNilEnrollAt(value *time.Time) *StudentUpdate {
	if value != nil {
		return s.SetEnrollAt(*value)
	}
	return s
}

// set field if value's pointer is not nil.
func (s *StudentUpdateOne) SetNotNilEnrollAt(value *time.Time) *StudentUpdateOne {
	if value != nil {
		return s.SetEnrollAt(*value)
	}
	return s
}

// set field if value's pointer is not nil.
func (s *StudentCreate) SetNotNilEnrollAt(value *time.Time) *StudentCreate {
	if value != nil {
		return s.SetEnrollAt(*value)
	}
	return s
}

// set field if value's pointer is not nil.
func (s *StudentUpdate) SetNotNilStatusBool(value *bool) *StudentUpdate {
	if value != nil {
		return s.SetStatusBool(*value)
	}
	return s
}

// set field if value's pointer is not nil.
func (s *StudentUpdateOne) SetNotNilStatusBool(value *bool) *StudentUpdateOne {
	if value != nil {
		return s.SetStatusBool(*value)
	}
	return s
}

// set field if value's pointer is not nil.
func (s *StudentCreate) SetNotNilStatusBool(value *bool) *StudentCreate {
	if value != nil {
		return s.SetStatusBool(*value)
	}
	return s
}

// set field if value's pointer is not nil.
func (t *TeacherUpdate) SetNotNilUpdatedAt(value *time.Time) *TeacherUpdate {
	if value != nil {
		return t.SetUpdatedAt(*value)
	}
	return t
}

// set field if value's pointer is not nil.
func (t *TeacherUpdateOne) SetNotNilUpdatedAt(value *time.Time) *TeacherUpdateOne {
	if value != nil {
		return t.SetUpdatedAt(*value)
	}
	return t
}

// set field if value's pointer is not nil.
func (t *TeacherCreate) SetNotNilUpdatedAt(value *time.Time) *TeacherCreate {
	if value != nil {
		return t.SetUpdatedAt(*value)
	}
	return t
}

// set field if value's pointer is not nil.
func (t *TeacherUpdate) SetNotNilName(value *string) *TeacherUpdate {
	if value != nil {
		return t.SetName(*value)
	}
	return t
}

// set field if value's pointer is not nil.
func (t *TeacherUpdateOne) SetNotNilName(value *string) *TeacherUpdateOne {
	if value != nil {
		return t.SetName(*value)
	}
	return t
}

// set field if value's pointer is not nil.
func (t *TeacherCreate) SetNotNilName(value *string) *TeacherCreate {
	if value != nil {
		return t.SetName(*value)
	}
	return t
}

// set field if value's pointer is not nil.
func (t *TeacherUpdate) SetNotNilAge(value *int) *TeacherUpdate {
	if value != nil {
		return t.SetAge(*value)
	}
	return t
}

// set field if value's pointer is not nil.
func (t *TeacherUpdateOne) SetNotNilAge(value *int) *TeacherUpdateOne {
	if value != nil {
		return t.SetAge(*value)
	}
	return t
}

// set field if value's pointer is not nil.
func (t *TeacherCreate) SetNotNilAge(value *int) *TeacherCreate {
	if value != nil {
		return t.SetAge(*value)
	}
	return t
}

// set field if value's pointer is not nil.
func (t *TeacherUpdate) SetNotNilAgeInt32(value *int32) *TeacherUpdate {
	if value != nil {
		return t.SetAgeInt32(*value)
	}
	return t
}

// set field if value's pointer is not nil.
func (t *TeacherUpdateOne) SetNotNilAgeInt32(value *int32) *TeacherUpdateOne {
	if value != nil {
		return t.SetAgeInt32(*value)
	}
	return t
}

// set field if value's pointer is not nil.
func (t *TeacherCreate) SetNotNilAgeInt32(value *int32) *TeacherCreate {
	if value != nil {
		return t.SetAgeInt32(*value)
	}
	return t
}

// set field if value's pointer is not nil.
func (t *TeacherUpdate) SetNotNilAgeInt64(value *int64) *TeacherUpdate {
	if value != nil {
		return t.SetAgeInt64(*value)
	}
	return t
}

// set field if value's pointer is not nil.
func (t *TeacherUpdateOne) SetNotNilAgeInt64(value *int64) *TeacherUpdateOne {
	if value != nil {
		return t.SetAgeInt64(*value)
	}
	return t
}

// set field if value's pointer is not nil.
func (t *TeacherCreate) SetNotNilAgeInt64(value *int64) *TeacherCreate {
	if value != nil {
		return t.SetAgeInt64(*value)
	}
	return t
}

// set field if value's pointer is not nil.
func (t *TeacherUpdate) SetNotNilAgeUint(value *uint) *TeacherUpdate {
	if value != nil {
		return t.SetAgeUint(*value)
	}
	return t
}

// set field if value's pointer is not nil.
func (t *TeacherUpdateOne) SetNotNilAgeUint(value *uint) *TeacherUpdateOne {
	if value != nil {
		return t.SetAgeUint(*value)
	}
	return t
}

// set field if value's pointer is not nil.
func (t *TeacherCreate) SetNotNilAgeUint(value *uint) *TeacherCreate {
	if value != nil {
		return t.SetAgeUint(*value)
	}
	return t
}

// set field if value's pointer is not nil.
func (t *TeacherUpdate) SetNotNilAgeUint32(value *uint32) *TeacherUpdate {
	if value != nil {
		return t.SetAgeUint32(*value)
	}
	return t
}

// set field if value's pointer is not nil.
func (t *TeacherUpdateOne) SetNotNilAgeUint32(value *uint32) *TeacherUpdateOne {
	if value != nil {
		return t.SetAgeUint32(*value)
	}
	return t
}

// set field if value's pointer is not nil.
func (t *TeacherCreate) SetNotNilAgeUint32(value *uint32) *TeacherCreate {
	if value != nil {
		return t.SetAgeUint32(*value)
	}
	return t
}

// set field if value's pointer is not nil.
func (t *TeacherUpdate) SetNotNilAgeUint64(value *uint64) *TeacherUpdate {
	if value != nil {
		return t.SetAgeUint64(*value)
	}
	return t
}

// set field if value's pointer is not nil.
func (t *TeacherUpdateOne) SetNotNilAgeUint64(value *uint64) *TeacherUpdateOne {
	if value != nil {
		return t.SetAgeUint64(*value)
	}
	return t
}

// set field if value's pointer is not nil.
func (t *TeacherCreate) SetNotNilAgeUint64(value *uint64) *TeacherCreate {
	if value != nil {
		return t.SetAgeUint64(*value)
	}
	return t
}

// set field if value's pointer is not nil.
func (t *TeacherUpdate) SetNotNilWeightFloat(value *float64) *TeacherUpdate {
	if value != nil {
		return t.SetWeightFloat(*value)
	}
	return t
}

// set field if value's pointer is not nil.
func (t *TeacherUpdateOne) SetNotNilWeightFloat(value *float64) *TeacherUpdateOne {
	if value != nil {
		return t.SetWeightFloat(*value)
	}
	return t
}

// set field if value's pointer is not nil.
func (t *TeacherCreate) SetNotNilWeightFloat(value *float64) *TeacherCreate {
	if value != nil {
		return t.SetWeightFloat(*value)
	}
	return t
}

// set field if value's pointer is not nil.
func (t *TeacherUpdate) SetNotNilWeightFloat32(value *float32) *TeacherUpdate {
	if value != nil {
		return t.SetWeightFloat32(*value)
	}
	return t
}

// set field if value's pointer is not nil.
func (t *TeacherUpdateOne) SetNotNilWeightFloat32(value *float32) *TeacherUpdateOne {
	if value != nil {
		return t.SetWeightFloat32(*value)
	}
	return t
}

// set field if value's pointer is not nil.
func (t *TeacherCreate) SetNotNilWeightFloat32(value *float32) *TeacherCreate {
	if value != nil {
		return t.SetWeightFloat32(*value)
	}
	return t
}

// set field if value's pointer is not nil.
func (t *TeacherUpdate) SetNotNilClassID(value *uuid.UUID) *TeacherUpdate {
	if value != nil {
		return t.SetClassID(*value)
	}
	return t
}

// set field if value's pointer is not nil.
func (t *TeacherUpdateOne) SetNotNilClassID(value *uuid.UUID) *TeacherUpdateOne {
	if value != nil {
		return t.SetClassID(*value)
	}
	return t
}

// set field if value's pointer is not nil.
func (t *TeacherCreate) SetNotNilClassID(value *uuid.UUID) *TeacherCreate {
	if value != nil {
		return t.SetClassID(*value)
	}
	return t
}

// set field if value's pointer is not nil.
func (t *TeacherUpdate) SetNotNilEnrollAt(value *time.Time) *TeacherUpdate {
	if value != nil {
		return t.SetEnrollAt(*value)
	}
	return t
}

// set field if value's pointer is not nil.
func (t *TeacherUpdateOne) SetNotNilEnrollAt(value *time.Time) *TeacherUpdateOne {
	if value != nil {
		return t.SetEnrollAt(*value)
	}
	return t
}

// set field if value's pointer is not nil.
func (t *TeacherCreate) SetNotNilEnrollAt(value *time.Time) *TeacherCreate {
	if value != nil {
		return t.SetEnrollAt(*value)
	}
	return t
}

// set field if value's pointer is not nil.
func (t *TeacherUpdate) SetNotNilStatusBool(value *bool) *TeacherUpdate {
	if value != nil {
		return t.SetStatusBool(*value)
	}
	return t
}

// set field if value's pointer is not nil.
func (t *TeacherUpdateOne) SetNotNilStatusBool(value *bool) *TeacherUpdateOne {
	if value != nil {
		return t.SetStatusBool(*value)
	}
	return t
}

// set field if value's pointer is not nil.
func (t *TeacherCreate) SetNotNilStatusBool(value *bool) *TeacherCreate {
	if value != nil {
		return t.SetStatusBool(*value)
	}
	return t
}
