// Code generated by goctl. DO NOT EDIT.
// Source: example.proto

package server

import (
	"context"

	"github.com/suyuan32/simple-admin-example-rpc/example"
	"github.com/suyuan32/simple-admin-example-rpc/internal/logic/school/teacher"
	"github.com/suyuan32/simple-admin-example-rpc/internal/svc"
)

type SchoolServer struct {
	svcCtx *svc.ServiceContext
	example.UnimplementedSchoolServer
}

func NewSchoolServer(svcCtx *svc.ServiceContext) *SchoolServer {
	return &SchoolServer{
		svcCtx: svcCtx,
	}
}

// Teacher management
func (s *SchoolServer) CreateOrUpdateTeacher(ctx context.Context, in *example.TeacherInfo) (*example.BaseResp, error) {
	l := teacher.NewCreateOrUpdateTeacherLogic(ctx, s.svcCtx)
	return l.CreateOrUpdateTeacher(in)
}

func (s *SchoolServer) GetTeacherList(ctx context.Context, in *example.TeacherPageReq) (*example.TeacherListResp, error) {
	l := teacher.NewGetTeacherListLogic(ctx, s.svcCtx)
	return l.GetTeacherList(in)
}

func (s *SchoolServer) DeleteTeacher(ctx context.Context, in *example.UUIDReq) (*example.BaseResp, error) {
	l := teacher.NewDeleteTeacherLogic(ctx, s.svcCtx)
	return l.DeleteTeacher(in)
}

func (s *SchoolServer) BatchDeleteTeacher(ctx context.Context, in *example.UUIDsReq) (*example.BaseResp, error) {
	l := teacher.NewBatchDeleteTeacherLogic(ctx, s.svcCtx)
	return l.BatchDeleteTeacher(in)
}
