// Code generated by goctl. DO NOT EDIT.
// Source: example.proto

package client

import (
	"context"

	"github.com/suyuan32/simple-admin-example-rpc/example"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	BaseResp          = example.BaseResp
	Empty             = example.Empty
	IDReq             = example.IDReq
	IDsReq            = example.IDsReq
	PageInfoReq       = example.PageInfoReq
	StatusCodeReq     = example.StatusCodeReq
	StatusCodeUUIDReq = example.StatusCodeUUIDReq
	StudentInfo       = example.StudentInfo
	StudentListResp   = example.StudentListResp
	StudentPageReq    = example.StudentPageReq
	TeacherInfo       = example.TeacherInfo
	TeacherListResp   = example.TeacherListResp
	TeacherPageReq    = example.TeacherPageReq
	UUIDReq           = example.UUIDReq
	UUIDsReq          = example.UUIDsReq

	School interface {
		// Teacher management
		CreateOrUpdateTeacher(ctx context.Context, in *TeacherInfo, opts ...grpc.CallOption) (*BaseResp, error)
		GetTeacherList(ctx context.Context, in *TeacherPageReq, opts ...grpc.CallOption) (*TeacherListResp, error)
		DeleteTeacher(ctx context.Context, in *UUIDReq, opts ...grpc.CallOption) (*BaseResp, error)
		BatchDeleteTeacher(ctx context.Context, in *UUIDsReq, opts ...grpc.CallOption) (*BaseResp, error)
	}

	defaultSchool struct {
		cli zrpc.Client
	}
)

func NewSchool(cli zrpc.Client) School {
	return &defaultSchool{
		cli: cli,
	}
}

// Teacher management
func (m *defaultSchool) CreateOrUpdateTeacher(ctx context.Context, in *TeacherInfo, opts ...grpc.CallOption) (*BaseResp, error) {
	client := example.NewSchoolClient(m.cli.Conn())
	return client.CreateOrUpdateTeacher(ctx, in, opts...)
}

func (m *defaultSchool) GetTeacherList(ctx context.Context, in *TeacherPageReq, opts ...grpc.CallOption) (*TeacherListResp, error) {
	client := example.NewSchoolClient(m.cli.Conn())
	return client.GetTeacherList(ctx, in, opts...)
}

func (m *defaultSchool) DeleteTeacher(ctx context.Context, in *UUIDReq, opts ...grpc.CallOption) (*BaseResp, error) {
	client := example.NewSchoolClient(m.cli.Conn())
	return client.DeleteTeacher(ctx, in, opts...)
}

func (m *defaultSchool) BatchDeleteTeacher(ctx context.Context, in *UUIDsReq, opts ...grpc.CallOption) (*BaseResp, error) {
	client := example.NewSchoolClient(m.cli.Conn())
	return client.BatchDeleteTeacher(ctx, in, opts...)
}
